<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Country;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pakistan = Country::where('name', 'Pakistan')->first();
        $australia = Country::where('name', 'Australia')->first();
        
        City::insert([
            ['name' => 'Karachi', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lahore', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Faisalabad', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Rawalpindi', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Multan', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hyderabad', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gujranwala', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Peshawar', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Quetta', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Islamabad', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sargodha', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sialkot', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bahawalpur', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sukkur', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Jhang', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sheikhupura', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Larkana', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gujrat', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mardan', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kasur', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Rahim Yar Khan', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sahiwal', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Okara', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wah', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Dera Ghazi Khan', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mirpur Khas', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Nawabshah', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mingora', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Chiniot', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kamoke', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mandi Burewala', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Jhelum', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sadiqabad', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Jacobabad', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Shikarpur', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Khanewal', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hafizabad', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kohat', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Muzaffargarh', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Khanpur', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gojra', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bahawalnagar', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Muridke', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Pak Pattan', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Abottabad', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tando Adam', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Jaranwala', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Khairpur', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Chishtian Mandi', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Daska', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Dadu', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mandi Bahauddin', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Ahmadpur East', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kamalia', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Khuzdar', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Vihari', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Dera Ismail Khan', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wazirabad', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Nowshera', 'country_id' => $pakistan->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Melbourne', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sydney', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Brisbane', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Perth', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Adelaide', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gold Coast', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cranbourne', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Canberra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Central Coast', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wollongong', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Ipswich', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hobart', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Geelong', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Townsville', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Newcastle', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cairns', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Darwin', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Ballarat', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Toowoomba', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bendigo', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mandurah', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Launceston', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mackay', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hervey Bay', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Buderim', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wagga Wagga', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Pakenham', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Port Macquarie', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Caloundra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Frankston', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sunbury', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gladstone', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bathurst', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Palmerston', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Southport', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Dandenong', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Warrnambool', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Quakers Hill', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mount Gambier', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Traralgon', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Whyalla', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Armidale', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Burnie', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Griffith', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mount Eliza', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Maroochydore', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Taree', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Banora Point', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lara', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cessnock', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Horsham', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Murray Bridge', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wallan', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Australind', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Ormeau', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Barwon Heads', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mount Barker', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Morwell', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Forster', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Penrith', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Goonellabah', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Leopold', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Campbelltown', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Rutherford', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Nambour', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Corinda', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Muswellbrook', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kingston', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Grafton', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bowral', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kingaroy', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Casino', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Swan Hill', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Parkes', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mudgee', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mount Evelyn', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Inverell', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Andergrove', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Nowra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Flemington', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Colac', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bargara', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Ballina', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mareeba', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Moss Vale', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Springwood', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Rye', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cowra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Beenleigh', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tweed Heads', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Emu Plains', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Charters Towers', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Katoomba', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mooroopna', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Maryborough', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Young', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Narre Warren North', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Clifton Springs', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Castlemaine', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kingscliff', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Fremantle', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Leeton', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Blaxland', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kyabram', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sanctuary Point', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Moama', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Merrimac', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Moree', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Murwillumbah', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Urraween', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bongaree', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bomaderry', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Ulverstone', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Dromana', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Helensburgh', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Seymour', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Port Augusta', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Burpengary', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Waterford', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Deniliquin', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Strathalbyn', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lennox Head', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Nambucca Heads', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wauchope', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tumut', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Nuriootpa', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tuncurry', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Yamba', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lakes Entrance', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kurri Kurri', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'North Mackay', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Yass', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mittagong', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cootamundra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cannonvale', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Point Vernon', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Palmwoods', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Leongatha', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Stawell', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Narrabri', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Whittlesea', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Corowa', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Inverloch', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'New Norfolk', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Richmond', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wynyard', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Woolgoolga', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Glen Innes', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Alstonville', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Worragee', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Glenbrook', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Nairne', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tahmoor', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Scone', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kiama Downs', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hazelbrook', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lithgow', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Encounter Bay', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Boulder', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Salamander Bay', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Albury', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bucasia', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Millicent', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Churchill', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Renmark', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wingham', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Maffra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Glenella', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Rasmussen', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tanunda', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Old Bar', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'George Town', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wyong', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Broadford', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Drysdale', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tatura', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cockatoo', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Deeragun', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Victor Harbor', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Latrobe', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Berri', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wellington', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Thirlmere', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Legana', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Temora', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'The Entrance', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mansfield', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gerringong', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Loxton', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Somerset', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Korumburra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Picton', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Trafalgar', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Pearcedale', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Numurkah', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Peregian Beach', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Narrandera', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Suffolk Park', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Buninyong', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Longford', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kerang', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Weston', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sawtell', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Silverdale', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Roxby Downs', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bay View', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lismore', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Merimbula', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Scarness', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lake Cathie', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Paynesville', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Perth', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Maddingley', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Proserpine', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cobar', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Aldgate', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Port Fairy', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Koo-Wee-Rup', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Penguin', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Beachmere', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Smithton', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'McLaren Vale', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Euroa', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bellingen', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mullumbimby', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tura Beach', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Eden', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Red Cliffs', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bogangar', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Shoalhaven Heads', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Blayney', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Stirling', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wilton', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kapunda', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Terranora', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Woori Yallock', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Saint Georges Basin', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Camperdown', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Culburra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Deloraine', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tea Gardens', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bonny Hills', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'McCrae', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'North Wonthaggi', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Thursday Island', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Urunga', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Vincentia', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'West Wyalong', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Howlong', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lawson', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Narooma', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Quirindi', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Condobolin', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Margate', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Aberdare', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Dodges Ferry', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gilgandra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Launching Place', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Goolwa', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Rutherglen', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hahndorf', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Willunga', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sandy Beach', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hadspen', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Beaconsfield Upper', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hill Top', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Williamstown', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Jindabyne', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Freeling', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lobethal', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'The Oaks', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Baxter', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Saint Arnaud', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Esperance', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Heddon Greta', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Freshwater', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Grenfell', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bangalow', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kawana Waters', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Orbost', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Manilla', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Camden Haven', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wallerawang', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wattleglen', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mulwala', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Barmera', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Windsor', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Woodside', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lyndoch', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Batehaven', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Queenstown', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Yarram', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Brunswick Heads', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Waikerie', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Westbury', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Yaroomba', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Curlewis', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Denman', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bourke', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Nathalia', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tathra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cobden', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Drummond Cove', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Canowindra', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Yarragon', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Walgett', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Surfside', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Seven Mile Beach', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'San Remo', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Greenwell Point', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Valley Heights', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Oakdale', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Yallourn North', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Innisfail', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mollymook', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Evandale', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Wahgunyah', 'country_id' => $australia->id, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),]
        ]);
    }
}
